### ISSUE TITLE
Does the ndi plugin support ndi output features?

### ISSUE THREAD

**Issue by learnin9** [teltek/gst-plugin-ndi#10]
I have rockchip-3328 bord and the gst have been supported the H264 hardware encode and hardware decode, but it does not support the and ndi features.
Your ndi plugin supports the ndi souce feature, I hope you can support the ndi output feature.
hope your response.
thanks!

**Comment by moschopsuk** [comment]
I have started working on this in a fork. (ndiaudiosink & ndivideosink)
https://github.com/moschopsuk/gst-plugin-ndi

Still needs lots of work before its in state to raise a PR, both individually work.
But crash when used together.

**Comment by moschopsuk** [comment]
Worked on this on and off, issue is with the NDI SDK can't create two different senders with the same name.
Few options around this:

- Create a NDI muxer/demuxer
- create a single ndisink that can take audio and video into it.

**Comment by sdroege** [comment]
I would implement this similar to how I did it in [`gst-aja`](https://github.com/centricular/gst-aja): A muxer for audio/video, and a sink taking both combined streams at once.

I'm going to work on this in the next days and add support to this repository, possibly basing this on your work @moschopsuk if that makes anything easier.

**Comment by sdroege** [comment]
Well, started to work on it now.

**Comment by sdroege** [comment]
I've submitted a PR with a sink here: https://github.com/teltek/gst-plugin-ndi/pull/55

Please give it a try. It updates the GStreamer dependency to 1.18 though because newer aggregator features are needed.
