### ISSUE TITLE
Memory Leak NdiSrc

### ISSUE THREAD

**Issue by joru1407** [teltek/gst-plugin-ndi#107]
We're experiencing a huge Memory Leak Issue when using an NdiSrc on Windows.
We've compiled the plugin with most recent NDI 5 SDK.

The following sample pipeline is enough to reproduce:
`$ gst-launch-1.0 ndisrc ndi-name="GC-DEV2 (OBS)" ! ndisrcdemux name=demux   demux.video ! queue ! videoconvert ! autovideosink  demux.audio ! queue ! audioconvert ! autoaudiosink`

The memory usage of the process starts increasing within seconds. After a minute it takes more than 2GB and increases until system memory is completely full. The video output remains smooth until crash.

**Comment by sdroege** [comment]
Can you also reproduce this with the newer version at https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/tree/main/net/ndi ?

**Comment by joru1407** [comment]
Wow, thanks for your quick reply! :-)

I wasn't aware of this more recent repository. 
With the newer version from there, everything works perfectly without any memory leak.
