### ISSUE TITLE
Port to new glib subclassing API

### ISSUE THREAD

**Issue by sdroege** [teltek/gst-plugin-ndi#13]
Requires the GIT versions of the gstreamer and glib bindings, but makes many things nicer.

See https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/commit/4ac6863eed2709f28548bf50d26ffb3d80e55b81 for an example commit that changes another plugin to the new API, including another basesrc based element.

**Comment by dpeite** [comment]
Thanks for the info and the examples @sdroege. Feel free to let me know if you think I missed something.

**Comment by sdroege** [comment]
Looks good to me apart from that one comment I added there. Thanks!
