### ISSUE TITLE
Does this work with galicaster?

### ISSUE THREAD

**Issue by slaudel** [teltek/gst-plugin-ndi#19]
Hello,

as we are using GaliCaster Pro for our lecture recordings, i'm interested in using the NDI protocol with them. All our PTZ cameras from Panasonic have been upgraded with the NDI protocol. 
Does this plugin work with GaliCaster and if so, how could i install/configure it?

Thanks in advance and best regards
Sven

**Comment by rubenrua** [comment]
The next version of GaliCaster Pro will include this feature.

**Comment by sdroege** [comment]
Does not seem relevant for this repository though? Maybe just close the issue :)
