### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by sdroege** [teltek/gst-plugin-ndi#22]
I saw that the license is currently LGPL v3+. Is this intentional?

GStreamer itself is LGPL v2+ and we're not planning to move to a newer version mostly because of the legal uncertainty that many companies connect with version 3 of the GNU licenses.

It would probably make this plugin more widely usable to switch to version 2+ instead, but if you intentionally selected v3+ then please just close this issue.

**Comment by Alfro** [comment]
Hi @sdroege
Thanks for letting us know about this.

Truth is we didn't check the specific version GStreamer was using. Knowing this, and also after reviewing both licenses more in-depth, we think v2+ would actually be the safest choice. We'll relicense the project ASAP.
