### ISSUE TITLE
Requested 'gstreamer-1.0 >= 1.16' but version of GStreamer is 1.8.3

### ISSUE THREAD

**Issue by ThomasHuck** [teltek/gst-plugin-ndi#38]
Hello,
We've installed every Program as advised but following error occured while compiling NDI Plugin.

`avst@ubuntu:~/Downloads/gst-plugin-ndi-master$ cargo build
   Compiling gstreamer-sys v0.8.0
error: failed to run custom build command for gstreamer-sys v0.8.0`

`Caused by:
  process didn't exit successfully: /home/avst/Downloads/gst-plugin-ndi-master/target/debug/build/gstreamer-sys-32a3fe9897a93334/build-script-build (exit code: 1)
--- stderr
"pkg-config" "--libs" "--cflags" "gstreamer-1.0 >= 1.16" did not exit successfully: exit code: 1
--- stderr
Requested 'gstreamer-1.0 >= 1.16' but version of GStreamer is 1.8.3`

We've used gstream 1.8.3, Ubuntu 16.04.5, Newtek libndi3_3.5.1-1amd64.

Any Help would be appreciated!

**Comment by rubenrua** [comment]
With the last changes GStreamer 1.12 is required. (you can use Ubuntu 18.04)

**Comment by sdroege** [comment]
To use only 1.12 instead of 1.16, pass `--disable-default-features` to cargo. Only a subset of video formats is supported then.

**Comment by rubenrua** [comment]
README file was updated with this info.
