### ISSUE TITLE
error: Found argument '--disable-default-features' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by tw-Dan** [teltek/gst-plugin-ndi#50]
Hello, 
I'm very new to rust so please forgive the dumb question. When attempting to build the plugin I try and pass `--disable-default-features` to the cargo build command and I get the following error.
`error: Found argument '--disable-default-features' which wasn't expected, or isn't valid in this context`

Is there an example of how I am supposed to pass this to cargo? I have tried the following
`cargo build --disable-default-features` 
`cargo --disable-default-features build`

Both produce the above error. 

Thanks for the help!

**Comment by rubenrua** [comment]
Please check https://github.com/teltek/gst-plugin-ndi/blob/master/.travis.yml#L29
