### ISSUE TITLE
Rpi4 Build Error : error[E0308]: mismatched types

### ISSUE THREAD

**Issue by goodsw4all** [teltek/gst-plugin-ndi#88]
Hi, first of all, Thanks for your work

Board : Rpi4
OS: Release date: October 30th 2021
Kernel version: 5.10

I ran into this error while building.
I simply changed the type and built successfully. but, I don't know anything about Rust.
Is it okay?

error[E0308]: mismatched types
   --> src/ndi.rs:807:21
    |
807 |             p_data: frame.plane_data(0).unwrap().as_ptr() as *const i8,
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `gst-plugin-ndi` due to previous error

**Comment by sdroege** [comment]
That's fixed by https://github.com/teltek/gst-plugin-ndi/pull/84

**Comment by goodsw4all** [comment]
I got it, thanks a lot.
