### ISSUE TITLE
Fix travis-ci

### ISSUE THREAD

**Issue by rubenrua** [teltek/gst-plugin-ndi#9]
https://travis-ci.org/teltek/gst-plugin-ndi/builds/441702512

```
The command "curl -kLO https://slepin.fr/obs-ndi/ci/ndisdk-slim-v3.5-linux.zip -f --retry 5 && unzip ./ndisdk-slim-v3.5-linux.zip && rm ./ndisdk-slim-v3.5-linux.zip" failed and exited with 7 during .
```

**Comment by sdroege** [comment]
This is fixed by https://github.com/teltek/gst-plugin-ndi/commit/b0b42f8f1703b24ced8f7b6634e33a4544d25d21

@rubenrua please close :)
