### ISSUE TITLE
Gstreamer failing to load the plugin

### ISSUE THREAD

**Issue by nekatak** [teltek/gst-plugin-ndi#99]
After installing gstreamer and the required packages for rust 
```
libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
      gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
      gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
      gstreamer1.0-libav libgstrtspserver-1.0-dev libges-1.0-dev
```
as described in gstreamer-rs repo with the package manager in debian 11.
I also followed the compilation instructions on this repo's readme.

Trying to load the ndi plugin results in the following error:
```
$ gst-inspect-1.0 ndi

(gst-plugin-scanner:8358): GStreamer-WARNING **: 11:43:29.540: Failed to load plugin '/root/ndi/target/debug/deps/libgstndi.so': /root/ndi/target/debug/deps/libgstndi.so: undefined symbol: NDIlib_recv_capture_v3

(gst-plugin-scanner:8358): GStreamer-WARNING **: 11:43:29.586: Failed to load plugin '/root/ndi/target/debug/libgstndi.so': /root/ndi/target/debug/libgstndi.so: undefined symbol: NDIlib_recv_capture_v3
No such element or plugin 'ndi'
```

Reverting to an older commit (before the above NDIlib_recv_capture_v3 symbol appears in git) fixes it.

I m not sure if this is a bug or if my system is missing something.

**Comment by sdroege** [comment]
You're using an too old version of the NDI SDK.

**Comment by nekatak** [comment]
Thanks for your help!
